# Generated by Django 4.1.7 on 2023-04-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_previous_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='previous_ratings',
            field=models.JSONField(blank=True, default=dict, verbose_name='Form rating'),
        ),
    ]
