export { default as Home } from './Home'
export { default as Dashboard } from './Dashboard'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Video } from './Video'
export { default as Score } from './Score'